package generate_test

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/orkspace/orkestra/pkg/tools/generate"
)

// scaffold is a test helper that calls KatalogScaffold with OutputFile set to
// a temp file so tests never touch the working directory. It returns the
// rendered YAML string so assertions can be made without reading the file.
func scaffold(t *testing.T, opts generate.KatalogScaffoldOptions) string {
	t.Helper()
	opts.OutputFile = filepath.Join(t.TempDir(), "katalog.yaml")
	out, err := generate.KatalogScaffold(opts)
	if err != nil {
		t.Fatalf("KatalogScaffold: unexpected error: %v", err)
	}
	return out
}

// scaffoldErr calls KatalogScaffold and asserts that it returns an error
// containing the given substring.
func scaffoldErr(t *testing.T, opts generate.KatalogScaffoldOptions, wantErrContains string) {
	t.Helper()
	opts.OutputFile = filepath.Join(t.TempDir(), "katalog.yaml")
	_, err := generate.KatalogScaffold(opts)
	if err == nil {
		t.Fatalf("KatalogScaffold: expected error containing %q, got nil", wantErrContains)
	}
	if !strings.Contains(err.Error(), wantErrContains) {
		t.Fatalf("error %q does not contain %q", err.Error(), wantErrContains)
	}
}

// assertContains fails the test if sub is not found in s.
func assertContains(t *testing.T, s, sub, label string) {
	t.Helper()
	if !strings.Contains(s, sub) {
		t.Errorf("%s: expected output to contain %q\n\nFull output:\n%s", label, sub, s)
	}
}

// assertAbsent fails the test if sub is found in s.
func assertAbsent(t *testing.T, s, sub, label string) {
	t.Helper()
	if strings.Contains(s, sub) {
		t.Errorf("%s: expected output NOT to contain %q\n\nFull output:\n%s", label, sub, s)
	}
}

// ── Mode tests ────────────────────────────────────────────────────────────────

func TestKatalogScaffold_DynamicDefault(t *testing.T) {
	out := scaffold(t, generate.KatalogScaffoldOptions{})

	// Header and apiVersion must be present.
	assertContains(t, out, `Generated by "ork generate katalog"`, "header")
	assertContains(t, out, "apiVersion: orkestra.orkspace.io/v1", "apiVersion")
	assertContains(t, out, "kind: Katalog", "kind")

	// Dynamic mode: default: true, no mode: typed.
	assertContains(t, out, "default: true", "default")
	assertAbsent(t, out, "mode: typed", "no typed mode")

	// Dynamic mode includes the declarative template comments.
	assertContains(t, out, "# onCreate:", "dynamic onCreate comment")
	assertContains(t, out, "# onReconcile:", "dynamic onReconcile comment")

	// Dynamic mode must NOT contain the hooks, constructor, or typed-only apiTypes fields.
	assertAbsent(t, out, "# hooks:", "no hooks in dynamic mode")
	assertAbsent(t, out, "# constructor:", "no constructor in dynamic mode")
	assertAbsent(t, out, "object: TODO", "no object field in dynamic mode")
	assertAbsent(t, out, "objectList: TODO", "no objectList field in dynamic mode")

	// workers must be correctly indented (6 spaces, same level as resync).
	assertContains(t, out, "      workers:", "workers at correct indent")
}

func TestKatalogScaffold_AddHook(t *testing.T) {
	out := scaffold(t, generate.KatalogScaffoldOptions{AddHook: true})

	assertContains(t, out, `Generated by "ork generate katalog --add-hook"`, "header flag suffix")
	assertContains(t, out, "mode: typed", "typed mode")
	assertContains(t, out, "default: true", "default true for hooks mode")
	assertContains(t, out, "# hooks:", "hooks section")
	assertContains(t, out, "ReconcileHooks[*MyKind]", "hook type hint")

	// Typed-mode apiTypes fields must be present.
	assertContains(t, out, "object: TODO", "object field")
	assertContains(t, out, "objectList: TODO", "objectList field")
	assertContains(t, out, "location: TODO", "location field")

	// Constructor section must be absent.
	assertAbsent(t, out, "# constructor:", "no constructor in hook mode")

	// Dynamic template comments must be absent.
	assertAbsent(t, out, "# onCreate:", "no dynamic blocks in typed mode")

	// workers must be correctly indented.
	assertContains(t, out, "      workers:", "workers at correct indent")
}

func TestKatalogScaffold_AddConstructor(t *testing.T) {
	out := scaffold(t, generate.KatalogScaffoldOptions{AddConstructor: true})

	assertContains(t, out, `Generated by "ork generate katalog --add-constructor"`, "header flag suffix")
	assertContains(t, out, "mode: typed", "typed mode")
	assertContains(t, out, "default: false", "default false for constructor mode")
	assertContains(t, out, "# constructor:", "constructor section")
	assertContains(t, out, "domain.Reconciler", "constructor return type hint")

	// Typed-mode apiTypes fields must be present.
	assertContains(t, out, "object: TODO", "object field")
	assertContains(t, out, "objectList: TODO", "objectList field")
	assertContains(t, out, "location: TODO", "location field")

	// Hooks section and dynamic blocks must be absent.
	assertAbsent(t, out, "# hooks:", "no hooks in constructor mode")
	assertAbsent(t, out, "# onCreate:", "no dynamic blocks")

	// workers must be correctly indented.
	assertContains(t, out, "      workers:", "workers at correct indent")
}

func TestKatalogScaffold_Typed_BothSections(t *testing.T) {
	out := scaffold(t, generate.KatalogScaffoldOptions{Typed: true})

	assertContains(t, out, `Generated by "ork generate katalog --typed"`, "header flag suffix")
	assertContains(t, out, "mode: typed", "typed mode")

	// Both sections must be present.
	assertContains(t, out, "# hooks:", "hooks section")
	assertContains(t, out, "# constructor:", "constructor section")

	// Typed-mode apiTypes fields must be present.
	assertContains(t, out, "object: TODO", "object field")
	assertContains(t, out, "objectList: TODO", "objectList field")
	assertContains(t, out, "location: TODO", "location field")

	// Dynamic template comments must be absent.
	assertAbsent(t, out, "# onCreate:", "no dynamic blocks")

	// workers must be correctly indented.
	assertContains(t, out, "      workers:", "workers at correct indent")
}

// ── Mutual-exclusivity validation ─────────────────────────────────────────────

func TestKatalogScaffold_MutualExclusion_HookAndConstructor(t *testing.T) {
	scaffoldErr(t,
		generate.KatalogScaffoldOptions{AddHook: true, AddConstructor: true},
		"mutually exclusive",
	)
}

func TestKatalogScaffold_MutualExclusion_HookAndTyped(t *testing.T) {
	scaffoldErr(t,
		generate.KatalogScaffoldOptions{AddHook: true, Typed: true},
		"mutually exclusive",
	)
}

func TestKatalogScaffold_MutualExclusion_ConstructorAndTyped(t *testing.T) {
	scaffoldErr(t,
		generate.KatalogScaffoldOptions{AddConstructor: true, Typed: true},
		"mutually exclusive",
	)
}

// ── Optional block: security ──────────────────────────────────────────────────

func TestKatalogScaffold_AddSecurity(t *testing.T) {
	out := scaffold(t, generate.KatalogScaffoldOptions{AddSecurity: true})

	assertContains(t, out, "--add-security", "flag in header")
	assertContains(t, out, "security:", "security block")
	assertContains(t, out, "namespaceProtection:", "namespaceProtection")
	assertContains(t, out, "deletionProtection:", "deletionProtection")
}

func TestKatalogScaffold_NoSecurity_WhenNotRequested(t *testing.T) {
	out := scaffold(t, generate.KatalogScaffoldOptions{})
	assertAbsent(t, out, "security:", "no security block in default mode")
}

// ── Optional block: notification ──────────────────────────────────────────────

func TestKatalogScaffold_AddNotification(t *testing.T) {
	out := scaffold(t, generate.KatalogScaffoldOptions{AddNotification: true})

	assertContains(t, out, "--add-notification", "flag in header")
	assertContains(t, out, "notification:", "notification block")
	assertContains(t, out, "enabled: true", "enabled field")
	assertContains(t, out, "defaults:", "defaults sub-block")
	assertContains(t, out, "slackWebhookUrl:", "slackWebhookUrl field (camelCase)")
	assertContains(t, out, "teams:", "teams map")
	// Teams must be a map (key: value), not a list (- name: ...).
	assertContains(t, out, "    platform:", "platform team key")
	assertContains(t, out, "    oncall:", "oncall team key")
	assertAbsent(t, out, "    - name: platform", "no list syntax in teams")
	// Email and slack must be lists.
	assertContains(t, out, "      email:", "email list field")
	assertContains(t, out, "        - platform@myorg.com", "email list entry")
	assertContains(t, out, "      slack:", "slack list field")
}

func TestKatalogScaffold_NoNotification_WhenNotRequested(t *testing.T) {
	out := scaffold(t, generate.KatalogScaffoldOptions{})
	assertAbsent(t, out, "notification:", "no notification block in default mode")
}

// ── Combination tests ─────────────────────────────────────────────────────────

func TestKatalogScaffold_HookWithAllOptionals(t *testing.T) {
	out := scaffold(t, generate.KatalogScaffoldOptions{
		AddHook:         true,
		AddSecurity:     true,
		AddNotification: true,
	})

	assertContains(t, out, "mode: typed", "typed")
	assertContains(t, out, "# hooks:", "hooks")
	assertContains(t, out, "security:", "security")
	assertContains(t, out, "notification:", "notification")
	assertAbsent(t, out, "# constructor:", "no constructor")
}

func TestKatalogScaffold_DynamicWithSecurityAndNotification(t *testing.T) {
	out := scaffold(t, generate.KatalogScaffoldOptions{
		AddSecurity:     true,
		AddNotification: true,
	})

	// Dynamic mode fields present.
	assertContains(t, out, "default: true", "default true")
	assertAbsent(t, out, "mode: typed", "no typed mode")

	// Optional blocks present.
	assertContains(t, out, "security:", "security block")
	assertContains(t, out, "notification:", "notification block")
}

// ── Output structure ──────────────────────────────────────────────────────────

func TestKatalogScaffold_AlwaysHasRequiredFields(t *testing.T) {
	// Every variant must produce a complete Katalog skeleton.
	cases := []generate.KatalogScaffoldOptions{
		{},
		{AddHook: true},
		{AddConstructor: true},
		{Typed: true},
	}
	required := []string{
		"apiVersion: orkestra.orkspace.io/v1",
		"kind: Katalog",
		"metadata:",
		"spec:",
		"crds:",
		"apiTypes:",
		"workers:",
		"resync:",
		"operatorBox:",
	}
	for _, opts := range cases {
		out := scaffold(t, opts)
		for _, field := range required {
			assertContains(t, out, field, "required field in "+flagSuffix(opts))
		}
	}
}

func flagSuffix(o generate.KatalogScaffoldOptions) string {
	switch {
	case o.AddHook:
		return "--add-hook"
	case o.AddConstructor:
		return "--add-constructor"
	case o.Typed:
		return "--typed"
	default:
		return "dynamic"
	}
}

// ── Validate unit tests ───────────────────────────────────────────────────────

func TestValidate_Valid(t *testing.T) {
	cases := []generate.KatalogScaffoldOptions{
		{},
		{AddHook: true},
		{AddConstructor: true},
		{Typed: true},
		{AddHook: true, AddSecurity: true},
	}
	for _, c := range cases {
		if err := c.Validate(); err != nil {
			t.Errorf("Validate(%+v): unexpected error: %v", c, err)
		}
	}
}

func TestValidate_Invalid(t *testing.T) {
	cases := []struct {
		opts    generate.KatalogScaffoldOptions
		wantErr string
	}{
		{generate.KatalogScaffoldOptions{AddHook: true, AddConstructor: true}, "mutually exclusive"},
		{generate.KatalogScaffoldOptions{AddHook: true, Typed: true}, "mutually exclusive"},
		{generate.KatalogScaffoldOptions{AddConstructor: true, Typed: true}, "mutually exclusive"},
		{generate.KatalogScaffoldOptions{AddHook: true, AddConstructor: true, Typed: true}, "mutually exclusive"},
	}
	for _, c := range cases {
		err := c.opts.Validate()
		if err == nil {
			t.Errorf("Validate(%+v): expected error containing %q, got nil", c.opts, c.wantErr)
			continue
		}
		if !strings.Contains(err.Error(), c.wantErr) {
			t.Errorf("Validate(%+v): error %q does not contain %q", c.opts, err.Error(), c.wantErr)
		}
	}
}
