package generate

import "text/template"

// registryTemplate emits zz_generated_typeregistry.go.
//
// This file registers compiled Go types and external functions into the
// package-level registries in pkg/types so Inrun can wire them at startup.
//
// What gets registered and why:
//
//	ObjectRegistry / ListRegistry
//	  Required when apiTypes.location is set (typed CRDs).
//	  The informer and REST client need factory functions that return the
//	  correct concrete Go type for a given GVK. Without these, the REST client
//	  cannot decode API server responses into Go structs.
//
//	HookRegistry
//	  Required when reconciler.hooks is declared.
//	  The hook function lives in an external package. The generator writes the
//	  import and a closure that calls the user's function. addHooks() reads
//	  this registry at startup and sets HookFactory on the CRD entry.
//
//	ReconcilerRegistry
//	  Required when reconciler.default: false and reconciler.constructor is declared.
//	  Same pattern as HookRegistry — external function, import + closure.
//
//	TargetHookRegistry
//	  Required when a serve.target entry declares reconciler.hooks with a different
//	  location than the CRD-level hooks binary. Keyed by GVK then target name.
//	  addTargetHooks() reads this at startup to set TargetHookFactories.
//
//	TargetReconcilerRegistry
//	  Required when a serve.target entry declares reconciler.default: false with
//	  its own constructor. Keyed by GVK then target name.
//	  addTargetConstructors() reads this at startup to set TargetReconcilerFactories.
//
//	RegisterTypedScheme
//	  Called by NewSchemeRegistry for typed CRDs.
//	  Each compiled API type package exports AddToScheme. This calls them all.
//	  Not needed for dynamic CRDs — they use *unstructured.Unstructured which
//	  the scheme already knows about.
//
// What does NOT get registered here:
//
//	Dynamic template CRDs (onCreate/onReconcile/onDelete blocks)
//	  These are handled entirely at runtime by generic.Reconciler.runTemplateReconcile().
//	  No registration needed. No generated file needed. inrun generate registry
//	  is not required for pure dynamic operators.
var registryTemplate = template.Must(template.New("registry").Parse(`// pkg/typeregistry/zz_generated_typeregistry.go
// Code generated by "inrun generate registry" on {{ .Timestamp }}. DO NOT EDIT.
// Re-generate by running: inrun generate registry --file <path-or-url>
//
// This file registers compiled Go types and external functions.
// Dynamic template CRDs do not appear here — they are handled at runtime
// by generic.Reconciler without any code generation.
package typeregistry

import (
	"github.com/inrundev/inrun/pkg/logger"
	"github.com/inrundev/inrun/pkg/types"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	{{ if .NeedsSchemeImports }}metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	{{ end }}{{ if or .NeedsHookImports .NeedsRecImports }}"github.com/inrundev/inrun/domain"
	{{ end }}{{ if .NeedsRecImports }}"github.com/inrundev/inrun/pkg/kubeclient"
	{{ end }}
{{ range .Imports }}	{{ .Alias }} "{{ .Location }}"
{{ end }})

// init runs before main(). It calls RegisterRuntimeObjects to populate the
// GVK-keyed registries and appends AddToScheme functions to SchemeAdderFns so
// that NewSchemeRegistry can find them through the internal pkg/typeregistry stub.
//
// A blank import of this package from main.go is the only wiring needed:
//
//	import _ "myapp/pkg/typeregistry"
// "inrun generate registry -k <catalog.yaml>" populates this
//
// No explicit call to RegisterRuntimeObjects or RegisterTypedScheme is required.
func init() {
	logger.Debug().Msg("typeregistry.init() started")
	RegisterRuntimeObjects()
{{ range .Entries }}	types.SchemeAdderFns = append(types.SchemeAdderFns, func(s *runtime.Scheme) error {
		s.AddKnownTypeWithName(schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}, &{{ .Alias }}.{{ .Object }}{})
		s.AddKnownTypeWithName(schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}List"}, &{{ .Alias }}.{{ .List }}{})
		metav1.AddToGroupVersion(s, schema.GroupVersion{Group: "{{ .Group }}", Version: "{{ .Version }}"})
		return nil
	})
{{ end }}	logger.Debug().Int("length", len(types.SchemeAdderFns)).Msg("typeregistry.init() finished")
}

// RegisterRuntimeObjects populates ObjectRegistry, ListRegistry, HookRegistry,
// and ReconcilerRegistry. Called by init() — do not call directly.
//
// Object/List entries — factory functions for typed CRDs.
//   Used by the informer to create zero-value instances for cache storage
//   and type assertion during reconciliation.
//
// Hook entries — factory functions for Go hook implementations.
//   Called by addHooks() during Catalog validation to wire HookFactory
//   onto the CRD entry. generic.Reconciler calls HookFactory() once at
//   startCRDWorkers time to obtain the typed hooks.
//
// Reconciler entries — constructor functions for custom reconcilers.
//   Called by addReconcilers() during Catalog validation to wire Constructor
//   onto the CRD entry. DependencyCoordinator calls Constructor() once at
//   startCRDWorkers time to build the reconciler.
func RegisterRuntimeObjects() {
	logger.Debug().Msg("RegisterRuntimeObjects called")
{{ range .Entries }}
	// {{ .Kind }} — typed CRD object and list factories
	types.ObjectRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() runtime.Object { return &{{ .Alias }}.{{ .Object }}{} }
	types.ListRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() runtime.Object { return &{{ .Alias }}.{{ .List }}{} }
{{ end }}
{{ if .HookEntries }}{{ range .HookEntries }}
	// {{ .Kind }} — Go hook factory
	// Calls {{ .Alias }}.{{ .Function }}() to obtain typed ReconcileHooks.
	types.HookRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func() domain.AnyReconcileHooks {
			return {{ .Alias }}.{{ .Function }}()
		}
{{ end }}{{ end }}
{{ if .RecEntries }}{{ range .RecEntries }}
	// {{ .Kind }} — custom reconciler constructor
	// Calls {{ .Alias }}.{{ .Function }}() to build the user's reconciler.
	types.ReconcilerRegistry[schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}] =
		func(kube kubeclient.Interface) domain.Reconciler {
			return {{ .Alias }}.{{ .Function }}(kube)
		}
{{ end }}{{ end }}
{{ if .TargetHookEntries }}{{ range .TargetHookEntries }}
	// {{ .Kind }}/{{ .TargetName }} — per-target Go hook factory
	// Distinct hook binary for this target; TargetHookFactories carries it into startCRDWorkers.
	{
		gvk := schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}
		if types.TargetHookRegistry[gvk] == nil {
			types.TargetHookRegistry[gvk] = map[string]func() domain.AnyReconcileHooks{}
		}
		types.TargetHookRegistry[gvk]["{{ .TargetName }}"] = func() domain.AnyReconcileHooks {
			return {{ .Alias }}.{{ .Function }}()
		}
	}
{{ end }}{{ end }}
{{ if .TargetRecEntries }}{{ range .TargetRecEntries }}
	// {{ .Kind }}/{{ .TargetName }} — per-target custom reconciler constructor
	// Distinct reconciler for this target; TargetReconcilerFactories carries it into startCRDWorkers.
	{
		gvk := schema.GroupVersionKind{Group: "{{ .Group }}", Version: "{{ .Version }}", Kind: "{{ .Kind }}"}
		if types.TargetReconcilerRegistry[gvk] == nil {
			types.TargetReconcilerRegistry[gvk] = map[string]types.NewReconcilerFunc{}
		}
		types.TargetReconcilerRegistry[gvk]["{{ .TargetName }}"] = func(kube kubeclient.Interface) domain.Reconciler {
			return {{ .Alias }}.{{ .Function }}(kube)
		}
	}
{{ end }}{{ end }}
	logger.Debug().
		Int("objectRegistrySize", len(types.ObjectRegistry)).
		Int("listRegistrySize", len(types.ListRegistry)).
		{{ if .HookEntries }}Int("hookRegistrySize", len(types.HookRegistry)).{{ end }}
		{{ if .RecEntries }}Int("reconcilerRegistrySize", len(types.ReconcilerRegistry)).{{ end }}
		{{ if .TargetHookEntries }}Int("targetHookRegistrySize", len(types.TargetHookRegistry)).{{ end }}
		{{ if .TargetRecEntries }}Int("targetRecRegistrySize", len(types.TargetReconcilerRegistry)).{{ end }}
		Msg("Runtime objects registered")
}
`))
