// pkg/typeregistry/zz_generated_typeregistry.go
// Code generated by "inrun generate registry" on 2026-03-19T12:05:02Z. DO NOT EDIT.
// Re-generate by running: inrun generate registry --file <path-or-url>
package typeregistry

import (
	"github.com/inrundev/inrun/pkg/types"
	"k8s.io/apimachinery/pkg/runtime"
)

func RegisterRuntimeObjects() {}

// RegisterTypedScheme drains types.SchemeAdderFns — functions registered by
// external generated packages via their init() calls. This is how the user's
// generated pkg/runtime wires its AddToScheme functions into NewSchemeRegistry
// without any explicit call beyond the blank import.
func RegisterTypedScheme(scheme *runtime.Scheme) (*runtime.Scheme, error) {
	for _, fn := range types.SchemeAdderFns {
		if err := fn(scheme); err != nil {
			return nil, err
		}
	}
	return scheme, nil
}
