apiVersion: orkestra.orkspace.io/v1
kind: Katalog
metadata:
  name: hello-website
  author: orkspace
  version: 0.1.0
  description: The simplest possible operator. One CRD, one Deployment.
  tags:
    - hello
    - beginner
    - web

spec:
  crds:
    website:
      apiTypes:
        group: demo.orkestra.io
        version: v1alpha1
        kind: Website
        plural: websites
      operatorBox:
        reconcile:
          onCreate:
            deployments:
              - image: "{{ .spec.image }}"
                # name defaults to: <cr-name>-deployment
                # namespace defaults to: <cr-namespace>
                # replicas defaults to: 1
        runtime:
          allowedNamespaces:
            - default

