// Code generated by "inrun generate registry" on 2026-09-19T08:56:13Z. DO NOT EDIT.
// Re-generate by running: inrun generate registry --file <path-or-url>
package main

import (
	"context"

	"github.com/inrundev/inrun/cmd/cli"
	"github.com/inrundev/inrun/pkg/config"
	"github.com/inrundev/inrun/pkg/logger"
	"github.com/inrundev/inrun/pkg/utils"

	_ "github.com/inrundev/inrun-args-hooks-targets/pkg/typeregistry"
)

func main() {
	kfg, err := config.Init()
	if err != nil {
		logger.Fatal().AnErr("failed to load configurations", err)
		utils.Exit(err)
	}
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	cli.Execute(kfg, ctx)
}
