// pkg/typeregistry/zz_generated_typeregistry.go
// Code generated by "ork generate registry" on 2026-07-18T21:41:44Z. DO NOT EDIT.
// Re-generate by running: ork generate registry --file <path-or-url>
//
// This file registers compiled Go types and external functions.
// Dynamic template CRDs do not appear here — they are handled at runtime
// by generic.Reconciler without any code generation.
package typeregistry

import (
	"github.com/orkspace/orkestra/domain"
	"github.com/orkspace/orkestra/pkg/logger"
	orktypes "github.com/orkspace/orkestra/pkg/types"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	rpv1alpha1 "github.com/orkspace/orkestra-resource-probe/api/v1alpha1"
	rphooks "github.com/orkspace/orkestra-resource-probe/hooks"
)

// init runs before main(). It calls RegisterRuntimeObjects to populate the
// GVK-keyed registries and appends AddToScheme functions to SchemeAdderFns so
// that NewSchemeRegistry can find them through the internal pkg/typeregistry stub.
//
// A blank import of this package from main.go is the only wiring needed:
//
//	import _ "myapp/pkg/typeregistry"
//
// "ork generate registry -k <katalog.yaml>" populates this
//
// No explicit call to RegisterRuntimeObjects or RegisterTypedScheme is required.
func init() {
	logger.Debug().Msg("typeregistry.init() started")
	RegisterRuntimeObjects()
	orktypes.SchemeAdderFns = append(orktypes.SchemeAdderFns, func(s *runtime.Scheme) error {
		s.AddKnownTypeWithName(schema.GroupVersionKind{Group: "resources.orkestra.io", Version: "v1alpha1", Kind: "ResourceProbe"}, &rpv1alpha1.ResourceProbe{})
		s.AddKnownTypeWithName(schema.GroupVersionKind{Group: "resources.orkestra.io", Version: "v1alpha1", Kind: "ResourceProbeList"}, &rpv1alpha1.ResourceProbeList{})
		metav1.AddToGroupVersion(s, schema.GroupVersion{Group: "resources.orkestra.io", Version: "v1alpha1"})
		return nil
	})
	logger.Debug().Int("length", len(orktypes.SchemeAdderFns)).Msg("typeregistry.init() finished")
}

// RegisterRuntimeObjects populates ObjectRegistry, ListRegistry, HookRegistry,
// and ReconcilerRegistry. Called by init() — do not call directly.
//
// Object/List entries — factory functions for typed CRDs.
//
//	Used by the informer to create zero-value instances for cache storage
//	and type assertion during reconciliation.
//
// Hook entries — factory functions for Go hook implementations.
//
//	Called by addHooks() during Katalog validation to wire HookFactory
//	onto the CRD entry. generic.Reconciler calls HookFactory() once at
//	startCRDWorkers time to obtain the typed hooks.
//
// Reconciler entries — constructor functions for custom reconcilers.
//
//	Called by addReconcilers() during Katalog validation to wire Constructor
//	onto the CRD entry. DependencyKordinator calls Constructor() once at
//	startCRDWorkers time to build the reconciler.
func RegisterRuntimeObjects() {
	logger.Debug().Msg("RegisterRuntimeObjects called")

	// ResourceProbe — typed CRD object and list factories
	orktypes.ObjectRegistry[schema.GroupVersionKind{Group: "resources.orkestra.io", Version: "v1alpha1", Kind: "ResourceProbe"}] =
		func() runtime.Object { return &rpv1alpha1.ResourceProbe{} }
	orktypes.ListRegistry[schema.GroupVersionKind{Group: "resources.orkestra.io", Version: "v1alpha1", Kind: "ResourceProbe"}] =
		func() runtime.Object { return &rpv1alpha1.ResourceProbeList{} }

	// ResourceProbe — Go hook factory
	// Calls rphooks.ResourceProbeHooks() to obtain typed ReconcileHooks.
	orktypes.HookRegistry[schema.GroupVersionKind{Group: "resources.orkestra.io", Version: "v1alpha1", Kind: "ResourceProbe"}] =
		func() domain.AnyReconcileHooks {
			return rphooks.ResourceProbeHooks()
		}

	logger.Debug().
		Int("objectRegistrySize", len(orktypes.ObjectRegistry)).
		Int("listRegistrySize", len(orktypes.ListRegistry)).
		Int("hookRegistrySize", len(orktypes.HookRegistry)).
		Msg("Runtime objects registered")
}
