apiVersion: e2e.inrun.dev/v1alpha1
kind: E2EProbe
metadata:
  name: my-probe-server
  namespace: default
spec:
  image: ghcr.io/inrundev/inrun-dev-server:latest
  replicas: 1
  port: 9999
  message: "e2e-ready"
---
apiVersion: e2e.inrun.dev/v1alpha1
kind: E2EProbe
metadata:
  name: my-probe-exec
  namespace: default
spec:
  image: nginx:alpine
  replicas: 1
  port: 80
  message: "e2e-ready"
