apiVersion: orkestra.orkspace.io/v1
kind: Katalog
metadata:
  name: website-with-serviceaccount
  author: orkspace
  version: 0.1.0
  description: >
    Adds a ServiceAccount to the website operator.
    The Deployment uses it immediately via serviceAccountName.
  tags:
    - web
    - rbac

spec:
  crds:
    website:
      crdFile: ./manifests/crd.yaml
      crFiles:
        - ./manifests/cr.yaml
      operatorBox:
        reconcile:
          onCreate:
            serviceAccounts:
              - name: "{{ .metadata.name }}-sa"

            deployments:
              - name: "{{ .metadata.name }}"
                image: "{{ .spec.image }}"
                replicas: "{{ .spec.replicas }}"
                port: "{{ .spec.port }}"
                serviceAccountName: "{{ .metadata.name }}-sa"
                reconcile: true

            services:
              - name: "{{ .metadata.name }}-svc"
                port: "80"
                targetPort: "{{ .spec.port }}"
                reconcile: true
        emit:
          status:
            fields:
              - path: phase
                value: "Running"
              - path: endpoint
                value: "{{ .metadata.name }}.{{ .metadata.namespace }}.svc.cluster.local"
              - path: allReplicasReady
                value: "{{ allReplicasReady .children.deployment }}"
        runtime:
          allowedNamespaces:
            - default

