apiVersion: demo.orkestra.io/v1
kind: WebApp
metadata:
  name: my-app-degraded
  namespace: default
spec:
  image: nginx:1.25
  healthCheckUrl: "http://orkestra-dev-server.orkestra-system.svc:9999/status/503"
  replicas: 1
