apiVersion: demo.orkestra.io/v1
kind: WebApp
metadata:
  name: my-app
  namespace: default
spec:
  image: nginx:1.25
  healthCheckUrl: "http://orkestra-dev-server.orkestra-system.svc:9999/health"
  replicas: 1
