//go:build ignore

// api/v1alpha1/database_types.go
//
// The Go type for the Database CRD.
// Generated by controller-gen from the CRD schema.
// Used by the typed hook — gives type-safe access to spec fields.
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// DatabaseSpec defines the desired state of Database
type DatabaseSpec struct {
	// Engine is the database engine: postgres or mysql
	Engine string `json:"engine"`

	// Version is the database version e.g. "14"
	Version string `json:"version,omitempty"`

	// Storage is the persistent volume size e.g. "10Gi"
	Storage string `json:"storage"`

	// Backup enables automated backup CronJob creation
	Backup bool `json:"backup,omitempty"`
}

// DatabaseStatus defines the observed state of Database
type DatabaseStatus struct {
	Phase      string             `json:"phase,omitempty"`
	Endpoint   string             `json:"endpoint,omitempty"`
	Conditions []metav1.Condition `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// Database is the Schema for the databases API
type Database struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   DatabaseSpec   `json:"spec,omitempty"`
	Status DatabaseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatabaseList contains a list of Database
type DatabaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Database `json:"items"`
}

var (
	GroupVersion  = schema.GroupVersion{Group: "demo.orkestra.io", Version: "v1alpha1"}
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)
	AddToScheme   = SchemeBuilder.AddToScheme
)

func addKnownTypes(scheme *runtime.Scheme) error {
	scheme.AddKnownTypes(GroupVersion,
		&Database{},
		&DatabaseList{},
	)
	metav1.AddToGroupVersion(scheme, GroupVersion)
	return nil
}

// DeepCopyObject implements runtime.Object
func (d *Database) DeepCopyObject() runtime.Object {
	if d == nil {
		return nil
	}
	out := new(Database)
	d.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all fields into out
func (d *Database) DeepCopyInto(out *Database) {
	*out = *d
	out.TypeMeta = d.TypeMeta
	d.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = d.Spec
	d.Status.DeepCopyInto(&out.Status)
}

func (s *DatabaseStatus) DeepCopyInto(out *DatabaseStatus) {
	*out = *s
	if s.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(s.Conditions))
		copy(out.Conditions, s.Conditions)
	}
}

// DatabaseList DeepCopyObject
func (dl *DatabaseList) DeepCopyObject() runtime.Object {
	if dl == nil {
		return nil
	}
	out := new(DatabaseList)
	*out = *dl
	if dl.Items != nil {
		out.Items = make([]Database, len(dl.Items))
		for i := range dl.Items {
			dl.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
	return out
}
