apiVersion: inrun.dev/v1
kind: Catalog
metadata:
  name: hello-website
  author: inrundev
  version: 0.1.0
  description: The canonical Inrun operator. One CRD, one Deployment, one Service.
  tags:
    - hello
    - web

spec:
  crds:
    website:
      crdFile: ./manifests/crd.yaml
      crFiles:
        - ./manifests/cr.yaml
      operatorBox:
        reconcile:
          onCreate:
            deployments:
              - name: "{{ .metadata.name }}"
                image: "{{ .spec.image }}"
                replicas: "{{ .spec.replicas }}"
                port: "{{ .spec.port }}"
                reconcile: true

            services:
              - name: "{{ .metadata.name }}-svc"
                port: "80"
                targetPort: "{{ .spec.port }}"
                reconcile: true
        emit:
          status:
            fields:
              - path: phase
                value: "Running"
              - path: endpoint
                value: "{{ .metadata.name }}.{{ .metadata.namespace }}.svc.cluster.local"
        runtime:
          allowedNamespaces:
            - default

