// pkg/typeregistry/zz_generated_typeregistry.go
// Code generated by "inrun generate registry" on 2026-09-19T06:43:58Z. DO NOT EDIT.
// Re-generate by running: inrun generate registry --file <path-or-url>
//
// This file registers compiled Go types and external functions.
// Dynamic template CRDs do not appear here — they are handled at runtime
// by generic.Reconciler without any code generation.
package typeregistry

import (
	"github.com/inrundev/inrun/domain"
	"github.com/inrundev/inrun/pkg/kubeclient"
	"github.com/inrundev/inrun/pkg/logger"
	"github.com/inrundev/inrun/pkg/types"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"

	webappv1 "github.com/inrundev/inrun-ctrlruntime-constructor/api/v1alpha1"
	webappconstructor "github.com/inrundev/inrun-ctrlruntime-constructor/constructor"
)

// init runs before main(). It calls RegisterRuntimeObjects to populate the
// GVK-keyed registries and appends AddToScheme functions to SchemeAdderFns so
// that NewSchemeRegistry can find them through the internal pkg/typeregistry stub.
//
// A blank import of this package from main.go is the only wiring needed:
//
//	import _ "myapp/pkg/typeregistry"
//
// "inrun generate registry -k <catalog.yaml>" populates this
//
// No explicit call to RegisterRuntimeObjects or RegisterTypedScheme is required.
func init() {
	logger.Debug().Msg("typeregistry.init() started")
	RegisterRuntimeObjects()
	types.SchemeAdderFns = append(types.SchemeAdderFns, func(s *runtime.Scheme) error {
		s.AddKnownTypeWithName(schema.GroupVersionKind{Group: "migration.demo.inrun.dev", Version: "v1alpha1", Kind: "WebApp"}, &webappv1.WebApp{})
		s.AddKnownTypeWithName(schema.GroupVersionKind{Group: "migration.demo.inrun.dev", Version: "v1alpha1", Kind: "WebAppList"}, &webappv1.WebAppList{})
		metav1.AddToGroupVersion(s, schema.GroupVersion{Group: "migration.demo.inrun.dev", Version: "v1alpha1"})
		return nil
	})
	logger.Debug().Int("length", len(types.SchemeAdderFns)).Msg("typeregistry.init() finished")
}

// RegisterRuntimeObjects populates ObjectRegistry, ListRegistry, HookRegistry,
// and ReconcilerRegistry. Called by init() — do not call directly.
//
// Object/List entries — factory functions for typed CRDs.
//
//	Used by the informer to create zero-value instances for cache storage
//	and type assertion during reconciliation.
//
// Hook entries — factory functions for Go hook implementations.
//
//	Called by addHooks() during Catalog validation to wire HookFactory
//	onto the CRD entry. generic.Reconciler calls HookFactory() once at
//	startCRDWorkers time to obtain the typed hooks.
//
// Reconciler entries — constructor functions for custom reconcilers.
//
//	Called by addReconcilers() during Catalog validation to wire Constructor
//	onto the CRD entry. DependencyCoordinator calls Constructor() once at
//	startCRDWorkers time to build the reconciler.
func RegisterRuntimeObjects() {
	logger.Debug().Msg("RegisterRuntimeObjects called")

	// WebApp — typed CRD object and list factories
	types.ObjectRegistry[schema.GroupVersionKind{Group: "migration.demo.inrun.dev", Version: "v1alpha1", Kind: "WebApp"}] =
		func() runtime.Object { return &webappv1.WebApp{} }
	types.ListRegistry[schema.GroupVersionKind{Group: "migration.demo.inrun.dev", Version: "v1alpha1", Kind: "WebApp"}] =
		func() runtime.Object { return &webappv1.WebAppList{} }

	// WebApp — custom reconciler constructor
	// Calls webappconstructor.NewWebAppReconciler() to build the user's reconciler.
	types.ReconcilerRegistry[schema.GroupVersionKind{Group: "migration.demo.inrun.dev", Version: "v1alpha1", Kind: "WebApp"}] =
		func(kube kubeclient.Interface) domain.Reconciler {
			return webappconstructor.NewWebAppReconciler(kube)
		}

	logger.Debug().
		Int("objectRegistrySize", len(types.ObjectRegistry)).
		Int("listRegistrySize", len(types.ListRegistry)).
		Int("reconcilerRegistrySize", len(types.ReconcilerRegistry)).
		Msg("Runtime objects registered")
}
