baseURL = "https://orkestra.sh/"
languageCode = "en-us"
title = "Orkestra"
enableGitInfo = true

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    codeFences = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2

[params]
  description = "Kubernetes operators without the infrastructure."
  github = "https://github.com/orkspace/orkestra"
  controlcenter = "https://cc.orkestra.sh"
  version = "v1"
  docsBase = "/docs/"

  [params.algolia]
    appId = "IDBZPZV9Q6"
    searchKey = "6eadbb67e7c72aaaa5309e17c4e1e9ad"
    indexName = "Orkestra Documentaion"

[menu]
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 1
  [[menu.main]]
    name = "Reference"
    url = "/docs/reference/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'
